server:
  port: 8080
## 39.108.67.248
spring:
  datasource:
    url: jdbc:mysql://43.226.43.150:3306/mysql1903076e9e_db?useUnicode=true&characterEncoding=utf-8
    username: mysql1903076e9e
    password: Howroad0701
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/mysql/*.xml
  type-aliases-package: qrCode.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
  